// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ippvvfvwgphucxvgjmow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcHZ2ZnZ3Z3BodWN4dmdqbW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTM4MjQsImV4cCI6MjA2OTI4OTgyNH0.n3FCy8QtAPJIaaOlpJH0wRJmKflmnNUCbLhOf40Ka9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});